# -*- coding: utf-8 -*-
"""learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ciAtEHbgrqaRpBilvtxPjKESQDQTmhq
"""

import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import drive
from tabulate import tabulate
drive.mount('/content/gdrive')

# 표 출력
def print_df(df):
    print(tabulate(df, headers='keys', tablefmt='psql'))

# 저장된 파일 가져오기
data = pd.read_csv('/content/gdrive/MyDrive/sample.csv')
# 검색할 값 추가하기. 
check =['나의식당',5,5,5,5,5,0,0,0,0,0]
data = data.append(pd.Series(check, index=data.columns), ignore_index=True)

# index를 보기 편하게 미리 지정한 idx로 바꿈. 추후에 idx가 식당 이름이 될 것으로 예상
data = data.set_index(keys=['식당이름'],drop=True)

print(data)

# cosine similarity 계산
similarity_rate = cosine_similarity(data, data)
print(similarity_rate)

# 계산한 값으로 유사도 표를 만듦
similarity_rate_df = pd.DataFrame(
    data=similarity_rate,
    index=data.index,
    columns=data.index
)

similarity_rate_df.head()

# 유사도 상위 5개 추천
def recommend(idx):
  indexs = similarity_rate_df[idx].sort_values(ascending=False)[:6]
  print_df(data.loc[indexs.index])
  print(indexs)

recommend('나의식당')

recommend('나의식당')